export const SET_LOADING = "SET_LOADING";
export const SET_UNLOADING = "SET_UNLOADING";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const SET_TRANSACTION = "SET_TRANSACTION";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";

export const SET_ERRORS = "SET_ERRORS";
export const SET_CREDENTIALS = "SET_CREDENTIALS";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
