export const SET_LOADING = "SET_LOADING";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const SET_TRANSACTION = "SET_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";

export const LOADING_USER = "LOADING_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_CREDENTIALS = "SET_CREDENTIALS";
export const SET_ERRORS = "SET_ERRORS";
